"""
This is a setup.py script generated by py2applet

Usage:
    python3 setup.py py2app
"""

from setuptools import setup

APP = ['Tasters-1.0.py']
DATA_FILES = [
    ("images", ["images/"]),
    ("music", ["music/"]),
    ("sounds", ["sounds/"])]
OPTIONS = {"iconfile": "icon.icns"}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
